const { NEXT_PUBLIC_CAP_SECRET, NEXT_PUBLIC_PLAYER_SECRET, NEXT_PUBLIC_MISTER_SECRET } = process.env

export const players = [
    {
        name: 'Amorim',
        number: 25,
        avatar: 'https://i.postimg.cc/52s2MBTB/amorim.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2003-06-25',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['PL'],
    },
    {
        name: 'Antunes',
        number: 4,
        avatar: 'https://i.postimg.cc/7PzhTTJ4/antunes.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1994-07-13',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DC', 'MDC'],
    },
    {
        name: 'Arantes',
        number: 26,
        avatar: 'https://i.postimg.cc/V6rtDkm1/arantes.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2003-05-02',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DC', 'DD'],
    },
    {
        name: 'Caetano',
        number: 9,
        avatar: 'https://i.postimg.cc/mDhv2cdz/caetano.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1994-06-07',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['PL'],
    },
    {
        name: 'Coruja',
        number: 14,
        avatar: 'https://i.postimg.cc/L4PfP5x3/corujinha.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1996-06-06',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DD', 'DC', 'DE', 'ME', 'MD'],
    },
    {
        name: 'Costa',
        number: 91,
        avatar: 'https://i.postimg.cc/ZKhRPK6d/costa.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1995-04-19',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DC', 'MDC'],
    },
    {
        name: 'Correia',
        number: 91,
        avatar: 'https://i.postimg.cc/02dNVRCH/correia.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2000-07-21',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DC'],
    },
    {
        name: 'Pedro Rodrigues',
        number: 0,
        avatar: 'https://i.postimg.cc/nVqVLbNc/rodrigues.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1994-05-09',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['ME', 'MD', 'EE', 'ED'],
    },
    {
        name: 'Castro',
        number: 31,
        avatar: 'https://i.postimg.cc/mDvHqWg9/castro.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2005-07-02',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['GR'],
    },
    {
        name: 'Cris',
        number: 1,
        avatar: 'https://i.postimg.cc/D01X3pSM/cris.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1994-06-21',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['GR'],
    },
    {
        name: 'Diogo Alves',
        number: 0,
        avatar: 'https://i.postimg.cc/m2qMMwj5/diogo-alves.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2005-02-15',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DC'],
    },
    {
        name: 'Diogo Reis',
        number: 0,
        avatar: 'https://i.postimg.cc/43nN4KRr/diogo-reis.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2001-08-07',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['PL'],
    },
    {
        name: 'Felipe',
        number: 0,
        avatar: 'https://i.postimg.cc/QMPNFXXV/felipe.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1993-08-31',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['EE', 'ED'],
    },
    {
        name: 'Gouveia',
        number: 0,
        avatar: 'https://i.postimg.cc/5NMzSJGd/gouveia.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2005-01-05',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['ME', 'MD'],
    },
    {
        name: 'Gui',
        number: 0,
        avatar: 'https://i.postimg.cc/HxyY5fxz/gui.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2005-10-05',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['ME', 'MD', 'DD'],
    },
    {
        name: 'Joãozinho',
        number: 18,
        avatar: 'https://i.postimg.cc/Hn1ptB8g/joaozinho.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1997-08-06',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DE', 'EE'],
    },
    {
        name: 'Gonçalo Lima',
        number: 0,
        avatar: 'https://i.postimg.cc/Dyg2qQ29/goncalo-lima.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2005-02-19',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DC'],
    },
    {
        name: 'Pinto',
        number: 0,
        avatar: 'https://i.postimg.cc/Cxhf9NSc/pinto.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2003-01-11',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['EE', 'ED'],
    },
    {
        name: 'Serra',
        number: 10,
        avatar: 'https://i.postimg.cc/dtvskNKR/serra.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '1999-06-07',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['ME', 'MD', 'EE', 'ED'],
    },
    {
        name: 'Tiago',
        number: 0,
        avatar: 'https://i.postimg.cc/QMP99Z5z/tiago.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2001-04-03',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DE', 'DC'],
    },
    {
        name: 'Ricardo Martins',
        number: 0,
        avatar: 'https://i.postimg.cc/N0L2jjyT/ricardo-martins.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2001-04-03',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['PL'],
    },
    {
        name: 'Miguel',
        number: 19,
        avatar: 'https://i.postimg.cc/9Ft7xS54/miguel.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2000-05-24',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DD'],
    },
    {
        name: 'Ricardo Fernandes',
        number: 20,
        avatar: 'https://i.postimg.cc/2S0BYZ5r/ricardo-fernandes.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2003-03-28',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['ME', 'MD'],
    },
    {
        name: 'Ricardo Moreira',
        number: 0,
        avatar: 'https://i.postimg.cc/fL93YqfR/ricardo-moreira.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2004-08-12',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['ME', 'MD'],
    },
    {
        name: 'Nélson',
        number: 0,
        avatar: 'https://i.postimg.cc/fL3b4PZd/nelson.png',
        assists: 0,
        goals: 0,
        fines: {
            total: 0,
            paid: 0,
            games: 0,
        },
        cards: { yellow: 0, red: 0 },
        dob: '2000-01-14',
        is_captain: false,
        points: {
            month: 0,
            total: 0,
        },
        positions: ['DC'],
    },
]

export const events = [
    {
        title: 'Exames e Apresentação',
        date: '2024-08-07',
        start: '15:00',
        end: '16:30',
        type: 'other',
    },
    {
        title: 'Treino',
        date: '2024-08-07',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-08',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino vs. AVES sub-19',
        date: '2024-08-10',
        start: '10:30',
        end: '12:15',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-12',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-13',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-14',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-15',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino vs Bougadense',
        date: '2024-08-05',
        start: '10:30',
        end: '12:45',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-19',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-20',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-21',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-22',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Torneio Valenciano',
        date: '2024-08-24',
        start: '15:30',
        end: '19:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-26',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-27',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-28',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-29',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-08-30',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Apresentação vs AVES sub-19',
        date: '2024-09-02',
        start: '18:00',
        end: '19:45',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-05',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-06',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-10',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-12',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-13',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-17',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-18',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-20',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-24',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-25',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-09-26',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-01',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-03',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-04',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-08',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-10',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-11',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-15',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-16',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-17',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-22',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-24',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-25',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-29',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-10-31',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-01',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-05',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-07',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-08',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-12',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-14',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-15',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-19',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-20',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-21',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-26',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-28',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-11-29',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-03',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-04',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-05',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-10',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-12',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-13',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-17',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-19',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-20',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-23',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-27',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2024-12-30',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    // 2025
    {
        title: 'Treino',
        date: '2025-01-02',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-03',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-06',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-07',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-09',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-10',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-14',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-15',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-16',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-21',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-23',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-24',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-28',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-30',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-01-31',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-04',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-05',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-06',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-11',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-13',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-14',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-18',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-19',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-20',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-25',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-26',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-02-27',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-03',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-06',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-07',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-11',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-12',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-13',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-18',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-20',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-21',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-25',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-27',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-03-28',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-01',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-03',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-04',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-08',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-10',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-11',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-15',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-16',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-17',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-22',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-24',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-25',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-29',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-04-30',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-01',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-06',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-08',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-09',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-13',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-15',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-16',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Possível treino final',
        date: '2025-05-20',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-22',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-23',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Possível treino final',
        date: '2025-05-28',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-05-30',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-06-03',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-06-05',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-06-06',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino',
        date: '2025-06-09',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Treino final',
        date: '2025-06-12',
        start: '20:00',
        end: '21:30',
        type: 'session',
    },
    {
        title: 'Bairro x St. Estevão',
        date: '2024-09-08',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Taipas x Bairro',
        date: '2024-09-15',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Bairro x Abação',
        date: '2024-09-22',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'S. Cristovão x Bairro',
        date: '2024-09-28',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Bairro x Antime',
        date: '2024-10-06',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Sta. Eulália x Bairro',
        date: '2024-10-13',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Pica x Bairro',
        date: '2024-10-19',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Bairro x St. Adrião',
        date: '2024-10-27',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Arco de Baúlhe x Bairro',
        date: '2024-11-03',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Taça AF Braga',
        date: '2024-11-10',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Bairro x Ronfe',
        date: '2024-11-17',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'S. Paio x Bairro',
        date: '2024-11-23',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Bairro x Lousado',
        date: '2024-12-01',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Berço x Bairro',
        date: '2024-12-07',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Bairro x Arões',
        date: '2024-12-15',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Taça AF Braga',
        date: '2024-12-22',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Jantar de Natal',
        date: '2024-12-22',
        start: '20:00',
        end: '24:00',
        type: 'other',
    },
    {
        title: 'Torcatense x Bairro',
        date: '2025-01-12',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'St. Estevão x Bairro',
        date: '2025-01-18',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Taça AF Braga',
        date: '2025-01-26',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Bairro x Taipas',
        date: '2025-02-02',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Abação x Bairro',
        date: '2025-02-08',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Bairro x S. Cristovão',
        date: '2025-02-16',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Antime x Bairro',
        date: '2025-02-22',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Bairro x Sta. Eulália',
        date: '2025-03-01',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Bairro x Pica',
        date: '2025-03-09',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Sto. Adrião x Bairro',
        date: '2025-03-15',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Bairro x Arco de Baúlhe',
        date: '2025-03-23',
        start: '15:00',
        end: '16:45',
        type: 'game',
    },
    {
        title: 'Ronfe x Bairro',
        date: '2025-03-30',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Bairro x S. Paio',
        date: '2025-04-06',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Lousado x Bairro',
        date: '2025-04-13',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Taça AF Braga',
        date: '2025-04-19',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Bairro x Berço',
        date: '2025-04-27',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Arões x Bairro',
        date: '2025-05-03',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Taça Af Braga Meia-final 1ª mão',
        date: '2025-05-11',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Bairro x Torcatense',
        date: '2025-05-18',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Taça Af Braga Meia-final 2ª mão',
        date: '2025-05-25',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
    {
        title: 'Taça AF Braga Final',
        date: '2025-06-10',
        start: '16:00',
        end: '17:45',
        type: 'game',
    },
]

export const users = [
    { username: 'antunes', role: 'cap', password: '1234', session_id: NEXT_PUBLIC_CAP_SECRET },
    { username: 'coruja', role: 'cap', password: '1234', session_id: NEXT_PUBLIC_CAP_SECRET },
    { username: 'cris', role: 'cap', password: '1234', session_id: NEXT_PUBLIC_CAP_SECRET },

    { username: 'amorim', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'arantes', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'caetano', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'costa', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'correia', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'pedro_rodrigues', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'diogo_alves', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'diogo_reis', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'felipe', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'gouveia', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'gui', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'joao', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'lima', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'pinto', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'serra', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'tiago', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'ricardo_martins', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'miguel', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'ricardo_fernandes', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'ricardo_moreira', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },
    { username: 'nelson', role: 'player', password: '1234', session_id: NEXT_PUBLIC_PLAYER_SECRET },

    { username: 'emanuel', role: 'mister', password: '1234', session_id: NEXT_PUBLIC_MISTER_SECRET },
]

export const games = [
    {
        is_home: true,
        date: {
            date: '2024-06-10',
            start: '16:00',
        },
        final_result: '5-0',
        half_time_result: '3-0',
        cards: {
            yellow: 2,
            red: 0,
        },
        weather: {
            temp: '25',
            condition: 'sunny',
        },
        teams: {
            bairro: {
                tactic: '4-4-2',
                initial: [
                    {
                        _id: '',
                        position: 'GR',
                        goals: '15',
                        cards: {
                            yellow: '18',
                            red: '69',
                        },
                        sub: '75',
                    },
                ],
                bench: [
                    {
                        _id: '',
                        position: 'GR',
                        goals: [],
                        cards: {
                            yellow: 0,
                            red: 0,
                        },
                        sub: '',
                    },
                ],
            },
            opponent: {},
        },
        opponent: 'Ruivães',
        pre_game: 'Lorem ipsum',
        pos_game: 'Lorem ipsum',
    },
    {
        is_home: false,
        date: {
            date: '2024-06-14',
            start: '16:00',
        },
        final_result: '1-2',
        half_time_result: '0-0',
        cards: {
            yellow: 4,
            red: 1,
        },
        weather: {
            temp: '18',
            condition: 'foggy',
        },
        teams: {
            bairro: {
                tactic: '4-4-2',
                initial: [
                    {
                        _id: '',
                        position: 'GR',
                        goals: [],
                        cards: {
                            yellow: [],
                            red: [],
                        },
                        sub: '',
                    },
                ],
                bench: [
                    {
                        _id: '',
                        position: 'GR',
                        goals: [],
                        cards: {
                            yellow: 0,
                            red: 0,
                        },
                        sub: '',
                    },
                ],
            },
            opponent: {},
        },
        opponent: 'Joane',
        pre_game: 'Lorem ipsum',
        pos_game: 'Lorem ipsum',
    },
    {
        is_home: false,
        date: {
            date: '2024-05-10',
            start: '16:00',
        },
        final_result: '3-2',
        half_time_result: '1-2',
        cards: {
            yellow: 4,
            red: 1,
        },
        weather: {
            temp: '18',
            condition: 'foggy',
        },
        teams: {
            bairro: {
                tactic: '4-4-2',
                initial: [
                    {
                        _id: '',
                        position: 'GR',
                        goals: [],
                        cards: {
                            yellow: [],
                            red: [],
                        },
                        sub: '',
                    },
                ],
                bench: [
                    {
                        _id: '',
                        position: 'GR',
                        goals: [],
                        cards: {
                            yellow: 0,
                            red: 0,
                        },
                        sub: '',
                    },
                ],
            },
            opponent: {},
        },
        opponent: 'Barcelona',
        pre_game: '',
        pos_game: '',
    },
    {
        is_home: true,
        date: {
            date: '2024-05-14',
            start: '16:00',
        },
        final_result: '3-3',
        half_time_result: '1-2',
        cards: {
            yellow: 4,
            red: 1,
        },
        weather: {
            temp: '18',
            condition: 'foggy',
        },
        teams: {
            bairro: {
                tactic: '4-4-2',
                initial: [
                    {
                        _id: '',
                        position: 'GR',
                        goals: [],
                        cards: {
                            yellow: [],
                            red: [],
                        },
                        sub: '',
                    },
                ],
                bench: [
                    {
                        _id: '',
                        position: 'GR',
                        goals: [],
                        cards: {
                            yellow: 0,
                            red: 0,
                        },
                        sub: '',
                    },
                ],
            },
            opponent: {},
        },
        opponent: 'Real Madrid',
        pre_game: 'Lorem ipsum',
        pos_game: 'Lorem ipsum',
    },
]
