import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Container } from '@mui/material'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import connectToMongoDB from '@/lib/db'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-slate-100 text-zinc-800`}>
                <Container className="min-h-screen flex flex-col w-full">
                    <Header />
                    <main className="py-12">{children}</main>
                    <Footer />
                </Container>
            </body>
        </html>
    )
}
